#!/usr/bin/perl
## -*- mode: perl; indent-tabs-mode: nil; perl-indent-level: 4 -*-
## vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=perl

use strict;
use warnings;
use JSON::XS;
use Data::Dumper;
use Getopt::Long;
BEGIN {
    if (!(exists $ENV{'TOOLBOX_HOME'} && -d "$ENV{'TOOLBOX_HOME'}/perl")) {
    print "This script requires libraries that are provided by the toolbox project.\n";
    print "Toolbox can be acquired from https://github.com/perftool-incubator/toolbox and\n";
    print "then use 'export TOOLBOX_HOME=/path/to/toolbox' so that it can be located.\n";
    exit 1;
    }
}
use lib "$ENV{'TOOLBOX_HOME'}/perl";
use toolbox::json;
use toolbox::metrics;

my $protocol;
my $remotehost;
my $ignore;
    # rx throughput is our primary_metric, but the unit is configureable 
    # by the "passthru" option which we donot know ahead of time.
    # So we will init primary_metric when we examine the outputs.
my $primary_metric;
my $result_file = "iperf-client-result.txt";
my %names = ('cmd' => 'write');
my %desc;
my %s;
my $ts;
my $ts_end;
my %times;
use constant SEC_TO_MSEC => 1000;

my $debug;

sub debug_print {
    if ( defined $debug ) {
        print "$_[0]";
    }
}

print "@ARGV\n";

GetOptions ("remotehost=s" => \$remotehost,
            "length=s" => \$ignore,
            "passthru=s" => \$ignore,
            "protocol=s" => \$protocol,
            "time=i" => \$ignore,
            "bitrate=s" => \$ignore,
            "ifname=s" => \$ignore,
            "cpu-pin=s" => \$ignore,
            );
#
# Extract begin/end timestamps recorded by the iperf run.
#
foreach my $i (qw(begin end)) {
    my $file = $i . ".txt";
    open(FH, $file) || die "Could not open " . $file;
    $times{$i} = int (<FH> * SEC_TO_MSEC);
    close FH; 
}

#
# process_proto - supports TCP and UDP.
#   UDP stats:  tx-UNIT/s, rx-UNITs, rx-lost/sec, rx-pps
#   TCP stats:  tx-UNIT/s, tx-retry/s, rx-Gbps
#   Where UNIT: Gbits, Mbits, Kbits, GBytes, Mbytes, Kbytes per CLI "--format" option.
# Note: if the user flips direction with "--reverse" option, the display context is still 
#       correct b/c we derive direction from outputs, not from "client" vs "server" clue.
# Note: the unit(s) are influenced by "--format" so we need to treat them dynamically.
# Note: the interval of time-series is configurable by "--interval" option. So we compute it.
#
sub process_proto {
    my $bitrate;
    my $interval;
    print "process_proto: enter\n";
    my $rateunit='none';

    (my $rc, my $fh) = open_read_text_file($result_file);
    if ($rc == 0 and defined $fh) {
        $ts=$times{'begin'};

        while (<$fh>) {
            if ( /sender/ or /receiver/ ) {
                # No use for entries in the summary section, after "- - - - "
                debug_print("Skip line: $_");
                $ts=$times{'begin'};    # Reset because we are about to process the Server section
                $rateunit = 'none';     # reset rate unit can change in the Server section.
                next;
            }
    
            # skip this special entry - HN it reports OOO
            if ( /SUM/ ) {
                next;
            }
            if ( $protocol eq "udp") {
                # Its output is as follows:
                #   [ ID] Interval           Transfer     Bitrate         Total Datagrams
                #   [  5]   0.00-1.00   sec   596 MBytes  5.00 Gbits/sec  38144
                #   < more similar entries >
                #    - - - - - - - - - - - - - - - - - - - - - - - - -
                #   [ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total  Datagrams
                #   [  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec  0.000 ms  0/1144389   (0%)      sender
                #   [  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec  0.012 ms  148/1144389 (0.013%)  receiver
                #
                #  Server output:
                #
                #   [ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
                #   [  5]   0.00-1.00   sec   596 MBytes  5.00 Gbits/sec  0.012 ms  8/38128 (0.021%)
                #   < more >
                #   - - - - - - - - - - - - - - - - - - - - - - - - -
                #   [ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
                #   [  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec  0.012 ms  148/1144389 (0.013%)  receiver

                if ( / sec / ) {
                    debug_print("Proc line: $_");
                    my $lost_total;
                    my @columns = split(/\s+/, $_);

                    # passthru CLI option "--interval nn" can change interval. So compute it.
                    my @tuble = split /-/, $columns[2];
                    my $start = $tuble[0];
                    my $end = $tuble[1];
                    my $sec_delta = $end - $start;

                    if ( $sec_delta == 0 )  {
                        # A nuissance. The last entry could be odd as below - Throw it away
                        # [  5]  10.00-10.00  sec   352 KBytes  7.99 Gbits/sec  0.012 ms  0/22 (0%)
                        next;
                    }

                    $interval = $sec_delta*SEC_TO_MSEC;
                    debug_print("interval=$interval\n"); 

                    $bitrate = $columns[6];
                    debug_print("bitrate $bitrate\n");

                    $rateunit = $columns[7];

                    # Always convert to common rate unit so results can be compared regardless of --format
                    my $rate_divisor = 1;
                    if ( $rateunit eq "Kbits/sec" ) {
                        $rateunit = "Gbps";
                        $bitrate /= 1000000;
                    } elsif ( $rateunit eq "Mbits/sec" ) {
                        $rateunit = "Gbps";
                        $bitrate /= 1000;
                    } elsif ( $rateunit eq "Gbits/sec" ) {
                        $rateunit = "Gbps";
                    } else {
                        printf "Error: Did not recongnize rate unit: %s\n", $rateunit;
                        exit 1;
                    }

                    $ts_end=$ts + $interval -1;
                    my $num_fields = scalar @columns;
                    if ( $num_fields > 10 ) {
                        $lost_total = $columns[10];
                        my @tuble = split /\//, $lost_total;
                        my $lost = $tuble[0];
                        my $total = $tuble[1];
                        debug_print("Lost:$lost Total:$total\n");

                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => 'rx-lost/sec');
                        %s = ('begin' => int $ts, 'end' => int $ts_end, 'value' =>  $lost);
                        log_sample("0", \%desc, \%names, \%s);

                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => 'rx-pps');
                        %s = ('begin' => int $ts, 'end' => int $ts_end, 'value' => $total);
                        log_sample("0", \%desc, \%names, \%s);

                        if ( ! defined  $primary_metric ) {
                            # rx throughput is our primary_metric.
                            $primary_metric = "rx-$rateunit";
                            debug_print("primary_metric $primary_metric\n");
                        }
                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => $primary_metric);

                    } else {
                        # no "Lost/Total" column implies tx section
                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => "tx-$rateunit");
                    }

                    # log rx "bitrate" sample
                    %s = ('begin' => int $ts, 'end' => int $ts_end, 'value' => $bitrate);
                    print ("begin: int $ts, end: int $ts_end\n");
                    log_sample("0", \%desc, \%names, \%s);
                    $ts=$ts+$interval;
                } else {
                    debug_print("Skip line: $_");
                }
            } else {
                # TCP outputs look as follows:
                #	[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
                #	[  5]   0.00-1.00   sec   596 MBytes  5.00 Gbits/sec    0   428 KBytes
                #	 < more>
                #	[ ID] Interval           Transfer     Bitrate         Retr
                #	[  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec    0             sender
                #	[  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec                  receiver
                #	
                #	Server output:
                #	[ ID] Interval           Transfer     Bitrate
                #	[  5]   0.00-1.00   sec   596 MBytes  5.00 Gbits/sec
                #	< more >
                #	- - - - - - - - - - - - - - - - - - - - - - - - -
                #	[ ID] Interval           Transfer     Bitrate
                #	[  5]   0.00-30.00  sec  17.5 GBytes  5.00 Gbits/sec                  receiver

                if ( /sec/ ) {
                    debug_print("Proc line: $_"); 
                    my $retry;
                    my @columns = split(/\s+/, $_);

                    # passthru CLI option "--interval nn" can change interval. So compute it.
                    my @tuble = split /-/, $columns[2];
                    my $start = $tuble[0];
                    my $end = $tuble[1];
                    my $sec_delta = $end - $start;
                    $interval = $sec_delta*SEC_TO_MSEC;
                    debug_print("interval=$interval\n");
                    
                    if ( $sec_delta == 0 )  {
                        # Exception. Last entry could be odd as below. Throw it away
                        # [  5]  10.00-10.00  sec   352 KBytes  7.99 Gbits/sec  0.012 ms  0/22 (0%)
                        next;
                    }
               
                    $bitrate = $columns[6];
                    debug_print("bitrate $bitrate\n"); 
                    $rateunit = $columns[7];

                    # Always convert to common rate unit so results can be compared regardless of --format
                    my $rate_divisor = 1;
                    if ( $rateunit eq "Kbits/sec" ) {
                        $rateunit = "Gbps";
                        $bitrate /= 1000000;
                    } elsif ( $rateunit eq "Mbits/sec" ) {
                        $rateunit = "Gbps";
                        $bitrate /= 1000;
                    } elsif ( $rateunit eq "Gbits/sec" ) {
                        $rateunit = "Gbps";
                    } else {
                        printf "Error: Did not recongnize rate unit: %s\n", $rateunit;
                        exit 1;
                    }
                    my $num_fields = scalar @columns;
                    debug_print("num_fields: $num_fields\n"); 
                    $ts_end=$ts + $interval -1;
                    if ( $num_fields > 8 ) {
                        $retry = $columns[8];
                        # log "Retr" sample
                        debug_print("Retry: $retry\n"); 

                        %desc = ('source' => 'iperf', 'class' => 'count', 'type' => 'tx-retry/sec');
                        %s = ('begin' => int $ts, 'end' => int $ts_end, 'value' =>  $retry);
                        log_sample("0", \%desc, \%names, \%s);

                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => "tx-$rateunit");
                    } else {
                        # no "Retr" column implies rx side
                        if ( ! defined  $primary_metric ) {
                            $primary_metric = "rx-$rateunit";
                            debug_print("primary_metric $primary_metric\n");
                        }
                        %desc = ('source' => 'iperf', 'class' => 'throughput', 'type' => $primary_metric);

                    }
                    # log rx "bitrate" sample
                    %s = ('begin' => int $ts, 'end' => int $ts_end, 'value' => $bitrate);

                    log_sample("0", \%desc, \%names, \%s);
                    $ts=$ts+$interval;
                } else {
                    debug_print("Skip line: $_");
                }
            } # TCP
        } # while

        close($fh);
        my $metric_data_name = finish_samples(1);
        # Associate the metrics with a benchmark-period (in this case "measurement")
        my %sample;
        my @periods;
        my %period = ('name' => 'measurement');
        $sample{'rickshaw-bench-metric'}{'schema'}{'version'} = "2021.04.12";
        my @metric_files = ( $metric_data_name );
        $period{'metric-files'} = \@metric_files;
        push(@periods, \%period);
        $sample{'periods'} = \@periods;
        $sample{'primary-period'} = 'measurement';
        $sample{'primary-metric'} = $primary_metric;
        $rc = put_json_file("post-process-data.json", \%sample);
        if ($rc > 0) {
            printf "iperf-post-process(): Could not write file post-process-data.json\n";
            exit 1
        }
    } else {
        printf "iperf-post-process(): open_read_text_file() failed with return code %d for file %s\n", $rc, $result_file;
        printf "Is the current directory for a iperf server (no result file)?\n";
    }
} 

process_proto();

# EOF
