#!/bin/bash
exec >iperf-server-stop-stderrout.txt 
exec 2>&1
echo "args; $@"

if [ -e iperf-server.pid ]; then
    pid=`cat iperf-server.pid`
    echo "Going to kill pid $pid"
    kill -15 $pid
    sleep 3
    if [ -e /proc/$pid ]; then
        echo "PID $pid still exists, trying kill -9"
        kill -9 $pid
    fi
    # Add END-TS timestamp for post-processing
    echo END-TS-0 $(date +%s.%N) >> iperf-server-result.txt
else
    echo "iperf-server.pid not found"
    echo "PWD: `/bin/pwd`"
    echo "LS: `/bin/ls`"
    exit 1
fi
